label_dict = {
    'f_pyrazole.log': 1,
    'h_indole.log': 2,
    'me_indole.log': 3,
    'cl_indole.log': 4,
    'tbu_indole.log': 5,
    'cl_nmeimidazole.log': 6,
    'f_nmeimidazole.log': 7,
    'h_meimidazolol.log': 8,
    'tbu_nmeimidazole.log': 9,
    'h_meimidazolamine.log': 16,
    'h_dimethylimidazole.log': 10,
    'h_nmeimidazole.log': 11,
    'no2_nmeimidazole.log': 13,
    'h_menitroimidazole.log': 14,
    'h_fnmeimidazole.log': 12,
    'h_meimidazolecarboxylic.log': 15,
    'me_metriazole.log': 17,
    'ethy_metriazole.log': 18,
    'cl_metriazole.log': 19,
    'f_metriazole.log': 20,
    'f_dimetriazole.log': 21,
    'ipr_metriazole.log': 22,
    'f_clmetriazole.log': 23,
    'ph_metriazole.log': 24,
    'f_cnmetriazole.log': 25,
    'tbu_metriazole.log': 26,
    'f_fmetriazole.log': 27,
    'mesityl_metriazole.log': 28,
    'f_metriazolamine.log': 29,
    'ccl3_metriazole.log': 30,
    'cn_metriazole.log': 31,
    'cyclo_metriazole.log': 32,
    'perfluorophenyl_metriazole.log': 33,
    'oh_metriazole.log': 34,
    '4meborinane_metriazole.log': 35,
    'cooh_metriazole.log': 36,
    'cf3_metriazole.log': 37,
    'h_metriazole.log': 38,
    'bicyclo_metriazole.log': 39,
    'no2_metriazole.log': 40,
    'borole_dimethylaniline.log': 41,
    'h_dimethylaniline.log': 42,
    'me_dimethylaniline.log': 43,
    'ethy_dimethylaniline.log': 44,
    'me_aniline.log': 45,
    'cl_dimethylaniline.log': 46,
    'me_tetramethylbenzopiperidine.log': 47,
    'f_dimethylaniline.log': 48,
    'f_tetramethylbenzopiperidine.log': 49,
    'ipr_dimethylaniline.out': 50,
    'ph_dimethylaniline.log': 51,
    '4meborinane_dimethylaniline.log': 52,
    'tbu_dimethylaniline.log': 53,
    'mesityl_dimethylaniline.log': 54,
    'cyclo_dimethylaniline.log': 55,
    'bicyclo_dimethylaniline.log': 56,
    'cyclo5_dimethylaniline.log': 57,
    'h_quinoline.log': 60,
    'me_benzopyrrolidine.log': 58,
    'f_quinoline.log': 61,
    'me_cinnoline.log': 59,
    'me_quinoline.log': 62,
    'cl_quinoline.log': 63,
    'tbu_quinoline.log': 64,
    'no2_quinoline.log': 65,
    'me_phquinolinamine.out': 66,
    'me_mequinolinamine.out': 67,
    'h_benzopiperidine.log': 68,
    'cl_benzopiperidine.log': 69,
    'f_benzopiperidine.log': 70,
    'me_benzopiperidine.log': 71,
    'tbu_benzopiperidine.log': 72,
    'cf3_benzopiperidine.log': 73,
    'no2_benzopiperidine.log': 74,
    'h_naphthalene.log': 75,
    'me_naphthalene.log': 76,
    'cl_naphthalene.log': 77,
    'tbu_naphthalene.log': 78,
    'me_indenoPy.log': 79,
    'tbu_indenoPy.log': 80,
    'f_indenoPy.log': 81,
    'h_biphenylene.log': 82,
    'tbu_biphenylene.log': 83,
    'me_biphenylene.log': 84,
    'cyclo_biphenylene.log': 85,
    'cl_biphenylene.log': 86,
    'f_biphenylene.log': 87,
    'bicyclo_biphenylene.log': 88,
    'ph_biphenylene.log': 89,
    'h_xanthene.log': 90,
    'me_xanthene.log': 91,
    'cyclo_xanthene.log': 92,
    'cl_xanthene.log': 93,
    'tbu_xanthene.log': 94,
    'bicyclo_xanthene.log': 95,
    'ph_xanthene.log': 96,
    'me_naphtoxanthene.log': 97,
    'cl_naphtoxanthene.log': 98,
    'ph_naphtoxanthene.log': 99,
    'tbu_naphtoxanthene.log': 100,
    'bicyclo_naphtoxanthene.log': 101,
    'me_Bbenzoxanthene.log': 102,
    'me_tribenzooxepine.log': 103,
    'h_dibenzofuran.log': 104,
    'f_dibenzofuran.log': 105,
    'me_dibenzofuran.log': 106,
    'ph_dibenzofuran.log': 107,
    'cl_dibenzofuran.log': 108,
    'tbu_dibenzofuran.log': 109,
    'cf3_dibenzofuran.log': 110,
    'cyclo_dibenzofuran.log': 111,
    'bicyclo_dibenzofuran.log': 112
}

family_dict = {
    'I':     range(1, 41),
    'II':    range(41, 75),
    'III':   range(75, 79),
    'IV':    range(79, 82),
    'V':     range(82, 90),
    'VI':    range(90, 103),
    'VII':   range(103, 104),
    'VIII':  range(104, 113)
}

external_label_dict = {
    '4meborinane_fmetriazole.log': 1,
    '4meborinane_fnmeimidazole.log': 2,
    'bicyclo_aniline.log': 3,
    'ccl3_aniline.log': 4,
    'cf3_dimetriazole.log': 5,
    'cf3_fnmeimidazole.log': 6,
    'cyclo5_benzopiperidine.log': 7,
    'oh_clmetriazole.log': 8,
    'BN_aniline_C5F5_C5F5_isopropyldimethylhydroquinoline19.log': 9,
    'BN_aniline_C5F5_C5F5_Me_Me.log': 10,
    'BN_aniline_C5F5_C5F5_Ph_Ph.log': 11,
    'BN_aniline_C5F5_C5F5_tetramethylpentane15.log': 12,
    'BN_aniline_Cl_Cl_tetramethylpentane15.log': 13,
    'BN_aniline_H_H_tetramethylpentane15.log': 14,
    'BN_aniline_mesityl_mesityl_tetramethylpentane15.log': 15,
    'BN_aniline_Ph_Ph_tetramethylpentane15.log': 16,
    'BN_aniline_pseudocumyl_pseudocumyl_Me_Me.log': 17,
    'BN_benzyl_C5F5_C5F5_tetramethylpentane15.log': 18,
    'BN_cyclohexanetrans_C5F5_C5F5_butane14.log': 19,
    'BN_cyclohexanetrans_C5F5_C5F5_pentane15.log': 20,
    'BN_dimethylphenylethyl_C5F5_C5F5_pentane15.log': 21,
    'BN_methylethyl_C5F5_C5F5_pentane15.log': 22,
    'BN_phenylethyl_C5F5_C5F5_ethyl_ethyl.log': 23,
    'BN_phenylethyl_C5F5_C5F5_pentane15.log': 24,
    'BN_quinoline_mesityl_mesityl.log': 25,
    'dfdmeobn_dbu.log': 26,
    'dfdmeobn_pyra.log': 27,
    'tfbn_dbu.log': 28,
    'tfbn_pyra.log': 29,
    'tmebn_dbu.log': 30,
    'azaborinine_phbenzophosphine.log': 31,
    'perf_tetrafphphosphane.log': 32,
    'phosphanylphenilborane_phosphanylphenilborane.log': 33,
    'bicyclo_alaniline.log': 34,
    'oh_alclmetriazole.log': 35,
    'pph_albbenzoxanthene.log': 36
}

external_family_dict = {
    'intra_B_N':     range(1, 26),
    'inter_B_N':     range(26, 31),
    'intra_B_P':     range(31, 34),
    'intra_Al_N':     range(34, 37)
}